### ISSUE TITLE
User Bio Metadata #TODO 📝

### ISSUE THREAD

**Issue by marrus-sh** [glitch-soc/mastodon#24]
I like the user metadata fields and people have expressed interest in them so I want to transition them from a cheap hack to a more fully-fledged feature! Here's what needs to happen:

- [ ] Better define the YAML frontmatter regex to match the spec 😉
- [ ] (Maybe?) Improve backwards-compatible frontmatter support (notably: support `&quot;` and `&apos;`)
- [ ] Intercept `simplified_format(account)` in `app/lib/formatter.rb` to NOT format YAML as HTML
    - VERY IMPORTANT in the case of hashtags, links, usernames
- [ ] Handle, at the very least, links ourselves (copy Mastodon's link regex if possible)
- [ ] Figure out and handle YAML character escaping
- [ ] Write up a spec defining what is and isn't recognized
- [ ] Improve input methods beyond plain-text in the bio entry field (?)
- [ ] Make profile metadata not count towards bio length (?)

**Comment by marrus-sh** [comment]
[aside: it should be noted:

1. that `js-yaml` is a dependency of Mastodon currently, and
2. that using it is overkill for our purposes, which can be accomplished purely through regex, but
3. that the frontmatter used in bios should be a well-formed subset of YAML, which is to say
4. that there shouldn't be anything we are able to parse that a proper YAML parser refuses to.

]

**Comment by 00dani** [comment]
Can we add `rel="me"` support to the todo list here? As discussed on tootsuite/mastodon#121 it's an important part of performing [distributed verification](http://www.kevinmarks.com/distributed-verify.html) across social profiles.

Not all links in the metadata should be considered `rel="me"` automatically, however. I suggest using YAML's tag feature to indicate which profile fields are "me", something like this:
```yaml
pronouns: https://pronoun.is/she/her
home: !me https://00dani.me
aka: !me @00dani@octodon.social, @00dani@glitch.social
friends: @page@awoo.space
```
which would be rendered as something similar to this (I know it doesn't actually use `<dt>` and `<dd>` but you get the idea):
```html
<dt>pronouns</dt>
<dd>
  <a href="https://pronoun.is/she/her" rel="nofollow noopener">pronoun.is/she/her</a>
</dd>

<dt>home</dt>
<dd>
  <a class="u-url" rel="me" href="https://00dani.me">00dani.me</a>
</dd>

<dt>aka</dt>
<dd>
  <a class="u-url mention" rel="me" href="https://octodon.social/@00dani">@00dani</a>,
  <a class="u-url mention" rel="me" href="https://glitch.social/@00dani">@00dani</a>
</dd>

<dt>friends</dt>
<dd>
  <a class="h-card mention" href="https://awoo.space/@page">@page</a>
</dd>
```

Notice I also adjusted how microformats2 is applied to mentions - !me mentions are rendered as `url` fields on *your* `h-card`, rather than nesting them inside another `h-card`. This makes the representative `h-card` for the user a lot more useful. 👍

**Comment by marrus-sh** [comment]
I'm a fan of this idea (and adding `!tags` to frontmatter in general) although it might be a while before we get it all working properly :P.

**Comment by AislingFae** [comment]
Is there a limit to how many items you can have? It seems to cap out at 5 but it doesn't seem to be stated anywhere in the documentation that that is the case.

**Comment by ThibG** [comment]
Indeed, it's limited to 5 items, and it is not documented.
Upstream has implemented a new way to handle such items, and is currently limited at 4 items, but this is more obvious in the interface.

**Comment by ThibG** [comment]
Can this issue be closed, as we have moved to upstream's implementation?
