### ISSUE TITLE
Images inside of CWs

### ISSUE THREAD

**Issue by marrus-sh** [glitch-soc/mastodon#38]
## Todo:

- [x] Put images inside of CWs for normal statuses
    - Implemented in 38a1299975e867c637c73b9ee5439cff08d08e96
- [x] Solve problems relating to sensitive media (#32)
    - Partially solved in 19690d3e3345b9231778280fb2098d350f46d632 and solved the rest of the way in b525caf40ac5e5332ff82042a6d9062d6f281688
- [x] Modify the CW button to show whether or not there is an image inside
    - Implemented in 99889ea57d04646d593dc5e9d0b1c8fe97856874 and improved in cc4cba8afd54de9cd2012119269fc3fc6836e865
- [x] Put images inside of CWs for detailed statuses
    - Implemented in 651c3d643c078abeb04099c2f1e54d335d60478f
- [x] Verify everything works on static pages
    - Implemented in fc65b691df3c1a0a9635ae337fd163c5336f87ce
- [x] Update the tootsuite PR accordingly
    - See tootsuite/mastodon#3979
