### ISSUE TITLE
App settings modal

### ISSUE THREAD

**Issue by marrus-sh** [glitch-soc/mastodon#39]
##  Todo:

- [x] Create the modal
    - Implemented in 595c6de32c052f2a5e21307a0e43a6bd5d4b5c88 with important bugfixes in 2d8ebdcc7215a4c0cae9cade954f4c9a4efc5070 and 0b371da971b96107d1afb1de97ce36d62e5d09aa
- [x] Add a setting for toggling wide view in desktop mode (#33)
    - Part of initial implementation
- [x] Add settings for configuring collapsed-toot functionality (#35)
    - Part of initial implementation
- [ ] Add additional settings from elsewhere (column settings, preferences) (depends on #30 for some features)
    - Letterboxed media settings added in ec2daae71ca03b414fa41a07e13e9653b0dff0a4
- [ ] Improve styling
- [ ] Improve language

**Comment by marrus-sh** [comment]
I'm going to close this since I think most of the remaining things can be handled by separate issues
